name: Deploy XHTML Visualisation

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write  # required by configure-pages

jobs:
  deploy-xhtml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload XHTML folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'xhtml-view'  # your folder containing index.html

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
